-- MySQL Script generated by MySQL Workbench
-- Tue Nov 27 16:27:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbhregistro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbhregistro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbhregistro` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema dbhistoriaclinica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbhistoriaclinica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbhistoriaclinica` DEFAULT CHARACTER SET utf8 ;
USE `dbhregistro` ;

-- -----------------------------------------------------
-- Table `dbhregistro`.`persona_trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbhregistro`.`persona_trabajador` (
  `idptrabajador` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `apaterno` VARCHAR(25) NOT NULL,
  `amaterno` VARCHAR(25) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `cargo_institucion` VARCHAR(45) NOT NULL,
  `modalidad_contrato` VARCHAR(45) NOT NULL,
  `tipo_documento` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`idptrabajador`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbhregistro`.`trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbhregistro`.`trabajador` (
  `idptrabajador` INT(11) NOT NULL,
  `num_documento` VARCHAR(8) NOT NULL,
  `celular` VARCHAR(9) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `fecha_registro` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idptrabajador`),
  UNIQUE INDEX `num_documento_UNIQUE` (`num_documento` ASC),
  CONSTRAINT `fk_persona_trabajador_trabajador`
    FOREIGN KEY (`idptrabajador`)
    REFERENCES `dbhregistro`.`persona_trabajador` (`idptrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbhregistro`.`acceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbhregistro`.`acceso` (
  `idacceso` INT(11) NOT NULL AUTO_INCREMENT,
  `idtrabajador` INT(11) NOT NULL,
  `acceso` VARCHAR(13) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idacceso`),
  UNIQUE INDEX `acceso_UNIQUE` (`acceso` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `estado_UNIQUE` (`estado` ASC),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC),
  INDEX `fk_trabajador_acceso_idx` (`idtrabajador` ASC),
  CONSTRAINT `fk_trabajador_acceso`
    FOREIGN KEY (`idtrabajador`)
    REFERENCES `dbhregistro`.`trabajador` (`idptrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbhregistro`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbhregistro`.`persona` (
  `idpersona` INT(11) NOT NULL AUTO_INCREMENT,
  `historia_clinica` VARCHAR(35) NOT NULL,
  `nombre` VARCHAR(35) NOT NULL,
  `apaterno` VARCHAR(25) NOT NULL,
  `amaterno` VARCHAR(25) NOT NULL,
  `tipo_seguro` VARCHAR(10) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(9) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `fecha_nacimiento` VARCHAR(20) NOT NULL,
  `sexo` VARCHAR(20) NOT NULL,
  `edad` VARCHAR(30) NOT NULL,
  `fa_nombres` VARCHAR(35) NOT NULL,
  `fa_apellidos` VARCHAR(35) NOT NULL,
  `fa_edad` VARCHAR(3) NOT NULL,
  `fa_direccion` VARCHAR(35) NOT NULL,
  `fecha_actual` VARCHAR(25) NOT NULL,
  `estado_civil` VARCHAR(10) NOT NULL,
  `tipo_documento` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `historia_clinica_UNIQUE` (`historia_clinica` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10153
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbhregistro`.`h_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbhregistro`.`h_paciente` (
  `idpersona` INT(11) NOT NULL,
  `codigo_paciente_dni` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `codigo_paciente_dni_UNIQUE` (`codigo_paciente_dni` ASC),
  CONSTRAINT `fk_persona_hpaciente`
    FOREIGN KEY (`idpersona`)
    REFERENCES `dbhregistro`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `dbhistoriaclinica` ;

-- -----------------------------------------------------
-- Table `dbhistoriaclinica`.`trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbhistoriaclinica`.`trabajador` (
  `idptrabajador` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `tipo_doc` VARCHAR(45) NOT NULL,
  `num_dni` VARCHAR(50) NOT NULL,
  `cargo_inst` VARCHAR(45) NOT NULL,
  `mod_cont` VARCHAR(45) NOT NULL,
  `num_cel` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `fecha_reg` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idptrabajador`),
  UNIQUE INDEX `num_dni_UNIQUE` (`num_dni` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbhistoriaclinica`.`acceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbhistoriaclinica`.`acceso` (
  `idacceso` INT(11) NOT NULL AUTO_INCREMENT,
  `idtrabajador` INT(11) NOT NULL,
  `acceso` VARCHAR(13) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idacceso`),
  UNIQUE INDEX `acceso_UNIQUE` (`acceso` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `estado_UNIQUE` (`estado` ASC),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC),
  INDEX `fk_trabajador_acceso_idx` (`idtrabajador` ASC),
  CONSTRAINT `fk_trabajador_acceso`
    FOREIGN KEY (`idtrabajador`)
    REFERENCES `dbhistoriaclinica`.`trabajador` (`idptrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbhistoriaclinica`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbhistoriaclinica`.`paciente` (
  `idpaciente` INT(45) NOT NULL,
  `idacceso` INT(45) NOT NULL,
  `usuario_acceso` VARCHAR(22) NULL DEFAULT NULL,
  `historia_clinica` VARCHAR(7) NULL DEFAULT NULL,
  `nombre` VARCHAR(30) NULL DEFAULT NULL,
  `apellidos` VARCHAR(34) NULL DEFAULT NULL,
  `tipo_seguro` VARCHAR(7) NULL DEFAULT NULL,
  `direccion` VARCHAR(44) NULL DEFAULT NULL,
  `celular` VARCHAR(9) NULL DEFAULT NULL,
  `email` VARCHAR(23) NULL DEFAULT NULL,
  `fecha_nac` VARCHAR(10) NULL DEFAULT NULL,
  `lugar_nac` VARCHAR(10) NULL DEFAULT NULL,
  `lugar_proc` VARCHAR(10) NULL DEFAULT NULL,
  `sexo` VARCHAR(9) NULL DEFAULT NULL,
  `edad` VARCHAR(29) NULL DEFAULT NULL,
  `fecha_reg` VARCHAR(10) NULL DEFAULT NULL,
  `estado_civil` VARCHAR(7) NULL DEFAULT NULL,
  `tipo_doc` VARCHAR(9) NULL DEFAULT NULL,
  `num_doc` VARCHAR(8) NULL DEFAULT NULL,
  `grado_instruc` VARCHAR(10) NULL DEFAULT NULL,
  `ocupacion` VARCHAR(10) NULL DEFAULT NULL,
  `religion` VARCHAR(10) NULL DEFAULT NULL,
  `fa_nombres` VARCHAR(24) NULL DEFAULT NULL,
  `fa_apellidos` VARCHAR(27) NULL DEFAULT NULL,
  `fa_edad` VARCHAR(2) NULL DEFAULT NULL,
  `fa_direccion` VARCHAR(35) NULL DEFAULT NULL,
  PRIMARY KEY (`idpaciente`),
  INDEX `fk_persona_acceso1_idx` (`idacceso` ASC),
  CONSTRAINT `fk_persona_acceso1`
    FOREIGN KEY (`idacceso`)
    REFERENCES `dbhistoriaclinica`.`acceso` (`idacceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 14066
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
