-- MySQL Script generated by MySQL Workbench
-- Fri Nov 16 12:35:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbhistoriaclinica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbhistoriaclinica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbhistoriaclinica` DEFAULT CHARACTER SET utf8 ;
USE `dbhistoriaclinica` ;

-- -----------------------------------------------------
-- Table `dbhistoriaclinica`.`trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbhistoriaclinica`.`trabajador` (
  `idptrabajador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `tipo_doc` VARCHAR(45) NOT NULL,
  `num_dni` VARCHAR(50) NOT NULL,
  `cargo_inst` VARCHAR(45) NOT NULL,
  `mod_cont` VARCHAR(45) NOT NULL,
  `num_cel` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `fecha_reg` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idptrabajador`),
  UNIQUE INDEX `num_dni_UNIQUE` (`num_dni` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbhistoriaclinica`.`acceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbhistoriaclinica`.`acceso` (
  `idacceso` INT NOT NULL AUTO_INCREMENT,
  `idtrabajador` INT NOT NULL,
  `acceso` VARCHAR(13) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idacceso`),
  INDEX `fk_trabajador_acceso_idx` (`idtrabajador` ASC),
  UNIQUE INDEX `acceso_UNIQUE` (`acceso` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `estado_UNIQUE` (`estado` ASC),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC),
  CONSTRAINT `fk_trabajador_acceso`
    FOREIGN KEY (`idtrabajador`)
    REFERENCES `dbhistoriaclinica`.`trabajador` (`idptrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbhistoriaclinica`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbhistoriaclinica`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `acceso_idacceso` INT NOT NULL,
  `usuario_reg` VARCHAR(100) NOT NULL,
  `historia_clinica` VARCHAR(35) NOT NULL,
  `nombre` VARCHAR(35) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `tipo_seguro` VARCHAR(10) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(9) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `fecha_nac` VARCHAR(10) NOT NULL,
  `lugar_nac` VARCHAR(256) NULL,
  `lugar_proc` VARCHAR(256) NULL,
  `sexo` VARCHAR(20) NOT NULL,
  `edad` VARCHAR(30) NOT NULL,
  `fecha_reg` VARCHAR(25) NOT NULL,
  `estado_civil` VARCHAR(10) NOT NULL,
  `tipo_doc` VARCHAR(10) NOT NULL,
  `num_doc` VARCHAR(8) NOT NULL,
  `grado_instruc` VARCHAR(256) NOT NULL,
  `ocupacion` VARCHAR(256) NOT NULL,
  `religion` VARCHAR(10) NOT NULL,
  `fa_nombres` VARCHAR(35) NOT NULL,
  `fa_apellidos` VARCHAR(35) NOT NULL,
  `fa_edad` VARCHAR(3) NOT NULL,
  `fa_direccion` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `historia_clinica_UNIQUE` (`historia_clinica` ASC),
  UNIQUE INDEX `dni_UNIQUE` (`num_doc` ASC),
  INDEX `fk_persona_acceso1_idx` (`acceso_idacceso` ASC),
  CONSTRAINT `fk_persona_acceso1`
    FOREIGN KEY (`acceso_idacceso`)
    REFERENCES `dbhistoriaclinica`.`acceso` (`idacceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
