/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.sql.Date;
import java.text.DateFormat;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Locale;
import java.util.Formatter;
import javax.swing.JOptionPane;
import reports.impHistoriaClinica;

/**
 *
 * @author Informatica
 */
public class frmReportes extends javax.swing.JInternalFrame {

    private String fecha_inicial;
    private String fecha_final;

    /**
     * Creates new form frmReportes
     */
    public frmReportes() {
        initComponents();
        lblfecha_inicial.setEnabled(false);
        lblfecha_final.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        dcofecha_final = new com.toedter.calendar.JDateChooser();
        dcofecha_inicial = new com.toedter.calendar.JDateChooser();
        lblfecha_inicial = new javax.swing.JLabel();
        lblfecha_final = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reporte");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("DE");

        jLabel2.setText("HASTA");

        jButton1.setText("PROCESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("REPORTE DE HISTORIAS CLINICAS");

        dcofecha_final.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcofecha_finalPropertyChange(evt);
            }
        });

        dcofecha_inicial.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcofecha_inicialPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel3)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblfecha_inicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(dcofecha_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dcofecha_final, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(lblfecha_final, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dcofecha_final, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dcofecha_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(9, 9, 9)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(lblfecha_final, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblfecha_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (lblfecha_inicial.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "INGRESE FECHA INICIAL");
            lblfecha_inicial.requestFocus();
            return;
        }
        if (lblfecha_final.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "INGRESE FECHA FINAL");
            lblfecha_final.requestFocus();
            return;
        }

        fecha_inicial = lblfecha_inicial.getText();
        fecha_final = lblfecha_final.getText();

        impHistoriaClinica rpmHistoriaClinica = new impHistoriaClinica();
        rpmHistoriaClinica.ReporteHistoriaClinica(fecha_inicial, fecha_final);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void dcofecha_finalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcofecha_finalPropertyChange
        // TODO add your handling code here:
        Formatter fmt = new Formatter();
        try {
            int f_dia = dcofecha_final.getCalendar().get(Calendar.DAY_OF_MONTH);

            int f_mes = dcofecha_final.getCalendar().get(Calendar.MONTH) + 1;
            String mes = null;
            int Agosto = 8;
            int Septiembre = 9;
            if (f_mes == 01) {
                mes = "01";
            } else if (f_mes == 02) {
                mes = "02";
            } else if (f_mes == 03) {
                mes = "03";
            } else if (f_mes == 04) {
                mes = "04";
            } else if (f_mes == 05) {
                mes = "05";
            } else if (f_mes == 06) {
                mes = "06";
            } else if (f_mes == 07) {
                mes = "07";
            } else if (f_mes == Agosto) {
                mes = "08";
            } else if (f_mes == Septiembre) {
                mes = "09";
            } else if (f_mes == 10) {
                mes = "10";
            } else if (f_mes == 11) {
                mes = "11";
            } else if (f_mes == 12) {
                mes = "12";
            }
            int f_año = dcofecha_final.getCalendar().get(Calendar.YEAR);

            lblfecha_final.setText(fmt.format("%02d", f_dia) + "/" + mes + "/" + f_año);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_dcofecha_finalPropertyChange

    private void dcofecha_inicialPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcofecha_inicialPropertyChange
//         TODO add your handling code here:
        Formatter fmt = new Formatter();
        try {
            int f_dia = dcofecha_inicial.getCalendar().get(Calendar.DAY_OF_MONTH);
            int f_mes = dcofecha_inicial.getCalendar().get(Calendar.MONTH) + 1;
            String mes = null;
            int Agosto = 8;
            int Septiembre = 9;
            if (f_mes == 01) {
                mes = "01";
            } else if (f_mes == 02) {
                mes = "02";
            } else if (f_mes == 03) {
                mes = "03";
            } else if (f_mes == 04) {
                mes = "04";
            } else if (f_mes == 05) {
                mes = "05";
            } else if (f_mes == 06) {
                mes = "06";
            } else if (f_mes == 07) {
                mes = "07";
            } else if (f_mes == Agosto) {
                mes = "08";
            } else if (f_mes == Septiembre) {
                mes = "09";
            } else if (f_mes == 10) {
                mes = "10";
            } else if (f_mes == 11) {
                mes = "11";
            } else if (f_mes == 12) {
                mes = "12";
            }
            int f_año = dcofecha_inicial.getCalendar().get(Calendar.YEAR);

            lblfecha_inicial.setText(fmt.format("%02d", f_dia) + "/" + mes + "/" + f_año);
        } catch (Exception e) {

        }

    }//GEN-LAST:event_dcofecha_inicialPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dcofecha_final;
    private com.toedter.calendar.JDateChooser dcofecha_inicial;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblfecha_final;
    private javax.swing.JLabel lblfecha_inicial;
    // End of variables declaration//GEN-END:variables

    private static java.sql.Date converUtilToSql(java.util.Date Fecha_I) {
        java.sql.Date sqlDate = new java.sql.Date(Fecha_I.getTime());
        return sqlDate;
    }

    private static java.sql.Date converUtilToSqlII(java.util.Date Fecha_F) {
        java.sql.Date sqlDateII = new java.sql.Date(Fecha_F.getTime());
        return sqlDateII;
    }

}
